@startuml
title CU-12 - Verificar Cupo Disponible en Empresa Pública

|Sistema de Gestión de Prácticas UPPA|
start

:Identificar que la empresa seleccionada
pertenece al sector público;

:Verificar cupos disponibles;

if (¿Existen cupos disponibles?) then (Sí)
  :Informar que la empresa posee
  cupos disponibles;
  stop

else (No)
  :Informar que la empresa pública
  seleccionada no posee cupos disponibles;

  :Volver al paso 1 del curso normal;
  stop
endif

@enduml