@startuml
title CU-13 - Proponer Tutor Académico Compatible

|Sistema de Gestión de Prácticas UPPA|
start

:Recibir la práctica profesional
seleccionada por el alumno;

:Cargar docentes de la universidad
registrados en el sistema;

if (¿Existen docentes registrados?) then (Sí)
  :Filtrar docentes con conocimientos
  en el área seleccionada;

  if (¿Existen tutores compatibles?) then (Sí)
    :Proponer tutor académico compatible;
    :Informar el tutor académico propuesto;
    stop

  else (No)
    :Informar que no existen tutores
    compatibles relacionados
    con el área profesional;

    :Volver al filtrado de docentes
    por área seleccionada;
    stop
  endif

else (No)
  :Informar que no existen
  docentes registrados;

  :Volver a recibir la práctica
  profesional seleccionada;
  stop
endif
@enduml