@startuml
title CU-05 - Registrar Empresa

|Administrador del Sistema|
start
:Acceder a "Registrar Empresa";

|Sistema|
:Mostrar formulario de alta;

|Administrador del Sistema|
:Ingresar datos de la empresa;

|Sistema|
:Validar datos obligatorios;

while (¿Datos obligatorios completos?) is (No)
  :Informar qué datos están incompletos;

  |Administrador del Sistema|
  :Completar información faltante;

  |Sistema|
  :Validar datos obligatorios;
endwhile (Sí)

:Validar que no exista otra empresa
con el mismo CUIT;

if (¿CUIT ya registrado?) then (Sí)
  :Informar que ya existe una empresa
  con ese CUIT;

  |Administrador del Sistema|
  if (¿Corregir CUIT?) then (Sí)
    :Corregir dato del CUIT;

    |Sistema|
    :Validar que no exista otra empresa
    con el mismo CUIT;

    if (¿CUIT ya registrado?) then (Sí)
      :Informar que ya existe una empresa
      con ese CUIT;
      stop
    else (No)
      |Administrador del Sistema|
      :Confirmar operación;

      |Sistema|
      :Registrar empresa;
      :Informar que el alta fue realizada correctamente;
      stop
    endif

  else (Cancelar)
    :Finalizar operación;
    stop
  endif

else (No)
  |Administrador del Sistema|
  :Confirmar operación;

  |Sistema|
  :Registrar empresa;
  :Informar que el alta fue realizada correctamente;
  stop
endif
@enduml
