@startuml
title CU-03 - Consultar Estado de Práctica Profesional

|Alumno|
start
:Seleccionar "Consultar estado\nde práctica profesional";

|Sistema|
:Recuperar la práctica profesional\nregistrada correspondiente al alumno;

:Obtener datos asociados;

:Mostrar el estado de la práctica\ny los datos asociados;

|Alumno|
:Visualizar información de la práctica;

stop
@enduml
