@startuml
title CU-14 - Seleccionar Responsable Compatible

|Sistema de Gestión de Prácticas UPPA|
start

:Recibir la práctica profesional
seleccionada por el alumno;

:Cargar responsables registrados
asociados a la empresa;

if (¿Existen responsables registrados?) then (Sí)

  :Filtrar responsables con conocimientos
  afines al área profesional;

  if (¿Existen responsables compatibles?) then (Sí)
    :Proponer responsables compatibles;
    :Informar los responsables compatibles;
    stop

  else (No)
    :Informar que no existen responsables
    con conocimientos afines
    al área profesional;

    :Volver a recibir la práctica
    profesional seleccionada;
    stop
  endif

else (No)
  :Informar que no existen responsables
  registrados para esa empresa;

  :Volver a recibir la práctica
  profesional seleccionada;
  stop
endif

@enduml