@startuml
title CU-09 - Consultar Convenios Próximos a Vencer

|Administrador del Sistema|
start
:Acceder a la opción de consulta;

|Sistema|
:Mostrar criterios de búsqueda y filtros;

|Administrador del Sistema|
:Ingresar uno o más criterios;

|Sistema|
:Validar criterios ingresados;

while (¿Parámetros válidos?) is (No)
  :Informar error de validación;

  |Administrador del Sistema|
  :Corregir los datos;

  |Sistema|
  :Validar criterios ingresados;
endwhile (Sí)

:Recuperar convenios cuyo vencimiento
se encuentra dentro del rango indicado;

if (¿Existen convenios próximos a vencer?) then (Sí)
  :Mostrar listado de convenios encontrados;

  |Administrador del Sistema|
  :Finalizar consulta;
  stop

else (No)
  :Informar que no existen convenios
  dentro del criterio indicado;

  |Administrador del Sistema|
  if (¿Modificar parámetros?) then (Sí)
    :Modificar parámetros de búsqueda;

    |Sistema|
    :Validar criterios ingresados;

    while (¿Parámetros válidos?) is (No)
      :Informar error de validación;

      |Administrador del Sistema|
      :Corregir los datos;

      |Sistema|
      :Validar criterios ingresados;
    endwhile (Sí)

    :Recuperar convenios cuyo vencimiento
    se encuentra dentro del rango indicado;

    if (¿Existen convenios próximos a vencer?) then (Sí)
      :Mostrar listado de convenios encontrados;

      |Administrador del Sistema|
      :Finalizar consulta;
      stop
    else (No)
      :Informar que no existen convenios
      dentro del criterio indicado;
      stop
    endif

  else (No)
    :Finalizar operación;
    stop
  endif
endif
@enduml
